apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: nodejs-app-multi-components-repo
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nodejs-app-multi-components-repo
    app.kubernetes.io/part-of: multi-components-repotest-app-170246361
  name: nodejs-app-multi-componenyuoc
spec:
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: nodejs-app-multi-components-repo
    weight: 100
status: {}
